@startuml

title: Use Case: Mood-entry

!define RECTANGLE class

skinparam usecase {
    BackgroundColor #D5DBDB
    BorderColor #B9FD99
    ArrowColor #49C191
}

skinparam actor {
    BackgroundColor #F5B7B1
    BorderColor #D5DBDB
}

' Define colors for components
!define USER_COLOR #D5DBDB
!define USE_CASE_COLOR #B9FD99

' Actors
actor :User: USER_COLOR

' Use Cases
usecase (Mood entry) USE_CASE_COLOR
usecase (Choose emotion) USE_CASE_COLOR
usecase (Give rating of emotion) USE_CASE_COLOR
usecase (Description) USE_CASE_COLOR
usecase (submit mood entry) USE_CASE_COLOR

' Connections
:User: --> (Mood entry)
(Mood entry) --> (Choose emotion)
(Choose emotion) --> (Give rating of emotion)
(Give rating of emotion) --> (Description)
(Description) --> (submit mood entry)

note right of (Description) : User can leave an \noptional description \nof their emotions

@enduml