@startuml
title Sequence Diagram: Update mood entry

actor User #D5DBDB
boundary MoodTrackerApp #966efc
control MoodController #99ebb9
control MoodService #7c93e5
database MoodRepository #9cc3f3
entity Mood #B1A4A4

!$color_success = '#d7f5b5'
!$color_failure = '#f19fa4'

participant User
participant MoodTrackerApp
participant MoodController
participant MoodService
participant MoodRepository
participant Mood

autonumber

User ->MoodTrackerApp: Opens App
activate User #D5DBDB
activate MoodTrackerApp #966efc
MoodTrackerApp -> User: Redirects to calendar
User -> MoodTrackerApp: User selects chosen day
MoodTrackerApp -> User: Redirects to selected day
User -> MoodTrackerApp: User selects mood entry
MoodTrackerApp -> User: Selected mood entry is displayed
User -> MoodTrackerApp: User chooses to delete mood entry
MoodTrackerApp -> User: Displays delete mood entry message
User -> MoodTrackerApp: User chooses delete mood entry
deactivate User

MoodTrackerApp -> MoodController: deleteMood(Long id)
deactivate MoodTrackerApp
activate MoodController #99ebb9

MoodController -> MoodService: deleteMood(Long id)
deactivate MoodController
activate MoodService #7c93e5

MoodService -> MoodRepository: deleteMood(Long id)
deactivate MoodService
activate MoodRepository #9cc3f3

MoodRepository -> Mood: deleteById(id)
deactivate MoodRepository
activate Mood #B1A4A4

group $color_failure Failed to delete mood entry

    Mood -> MoodRepository: return exception
    activate MoodRepository #9cc3f3

    MoodRepository -> MoodService: return exception
    deactivate MoodRepository
    activate MoodService #7c93e5

    MoodService -> MoodController: return exception
    deactivate MoodService
    activate MoodController #99ebb9

    MoodController -> MoodTrackerApp: return GlobalExceptionHandler
    deactivate MoodController
    activate MoodTrackerApp #966efc

    MoodTrackerApp -> User: Error message
    deactivate MoodTrackerApp
    activate User #D5DBDB

    group $color_success Succes deleting mood entry

        Mood -> MoodRepository: return void
        deactivate Mood
        activate MoodRepository #9cc3f3

        MoodRepository -> MoodService: return deleteById(id)
        deactivate MoodRepository
        activate MoodService #7c93e5

        MoodService -> MoodController: return moodRepository.deleteById(id)
        deactivate MoodService
        activate MoodController #99ebb9

        MoodController -> MoodTrackerApp: return responseEntity
        deactivate MoodController
        activate MoodTrackerApp #966efc

        MoodTrackerApp -> User: Message mood entry is deleted
        MoodTrackerApp -> User: User is directed to selected day
        deactivate MoodTrackerApp
        deactivate User

    end
end


@enduml