@startuml
title Sequence Diagram: User Registration

actor User #D5DBDB
boundary MoodTrackerApp #966efc
control EmailValidator #80d0a1
control PasswordValidator #bee959
control AuthenticationController #99ebb9
control UserService #7c93e5
database UserRepository #9cc3f3
entity Users #B1A4A4

!$color_success = '#d7f5b5'
!$color_failure = '#f19fa4'

participant User
participant MoodTrackerApp
participant EmailValidator
participant PasswordValidator
participant AuthenticationController
participant UserService
participant UserRepository
participant Users

autonumber

User -> MoodTrackerApp: Opens app
activate User #D5DBDB
activate MoodTrackerApp #966efc
MoodTrackerApp -> User: Redirects to Login or Registration
User -> MoodTrackerApp: User chooses Registration
MoodTrackerApp -> User: Displays registration form
User -> MoodTrackerApp: Fill in email

MoodTrackerApp -> EmailValidator: emailValidator(ValidEmail validEmail)
activate EmailValidator #80d0a1

group $color_failure Invalid Email

    EmailValidator -> MoodTrackerApp: return false

    MoodTrackerApp -> User: Message invalid email

    group $color_success Valid Email

        EmailValidator -> MoodTrackerApp: return true
        deactivate EmailValidator

        MoodTrackerApp -> User: Valid email

        User -> MoodTrackerApp: Fill in password

        MoodTrackerApp -> PasswordValidator: passwordValidator(ValidPassword validPassword)
        activate PasswordValidator #bee959

        group $color_failure Invalid password

            PasswordValidator -> MoodTrackerApp: return false

            MoodTrackerApp -> User: Message invalid password

            group $color_success Valid password

                PasswordValidator -> MoodTrackerApp: return true
                deactivate PasswordValidator

                MoodTrackerApp -> User: Valid email

                User -> MoodTrackerApp: Submit registration form
                deactivate User

                MoodTrackerApp -> AuthenticationController: register(UserDTO userDTO)
                deactivate MoodTrackerApp
                activate AuthenticationController #99ebb9

                AuthenticationController -> UserService: addUser(UserDTO userDTO)
                deactivate AuthenticationController
                activate UserService #7c93e5

                UserService -> UserRepository: addUser(User user)
                deactivate UserService
                activate UserRepository #9cc3f3

                UserRepository -> Users: save(User user)
                deactivate UserRepository
                activate Users #B1A4A4

                group $color_failure Registration failed

                    Users -> UserRepository: return exception
                    activate UserRepository #9cc3f3

                    UserRepository -> UserService: return exception
                    deactivate UserRepository
                    activate UserService #7c93e5

                    UserService -> AuthenticationController: return exception
                    deactivate UserService
                    activate AuthenticationController #99ebb9

                    AuthenticationController -> MoodTrackerApp: return GlobalExceptionHandler
                    deactivate AuthenticationController
                    activate MoodTrackerApp #966efc

                    MoodTrackerApp -> User: Error message
                    deactivate MoodTrackerApp
                    activate User #D5DBDB

                    group $color_success Registration succes

                        Users -> UserRepository: return user
                        deactivate Users
                        activate UserRepository #9cc3f3

                        UserRepository -> UserService: return save(User user)
                        deactivate UserRepository
                        activate UserService #7c93e5

                        UserService -> AuthenticationController: return mapUserToUserDTO(user)
                        deactivate UserService
                        activate AuthenticationController #99ebb9

                        AuthenticationController -> MoodTrackerApp: return responseEntity
                        deactivate AuthenticationController
                        activate MoodTrackerApp #966efc

                        MoodTrackerApp -> User: Message User is created
                        MoodTrackerApp -> User: User is directed to login
                        deactivate MoodTrackerApp
                        deactivate User
                   end
               end
            end
        end
    end
end

@enduml